### ISSUE TITLE
One or more indices is missing, please create them.

### ISSUE THREAD

**Issue by persiljehamn** [Epinova/Epinova.Elasticsearch#181]
I got this error when i try to run; Elasticsearch: Index CMS content.
I have Index in elasticsearch with same name

Processed 0 batches, for a total of 0 items to Elasticsearch index.

One or more indices is missing, please create them.

Stacktrace:
at Epinova.ElasticSearch.Core.EPiServer.Plugin.IndexEPiServerContent.Execute() in C:\projects\epinova-elasticsearch\src\Epinova.ElasticSearch.Core.EPiServer\Plugin\IndexEPiServerContent.cs:line 89

**Comment by otanum** [comment]
Related to https://github.com/Epinova/Epinova.Elasticsearch/releases/tag/v11.7.4.214?

Changed index names to support specific cultures.

**Comment by persiljehamn** [comment]
Are there exemple how index names should be to support specific cultures?

**Comment by otanum** [comment]
Just recreate indices with same name. You will notice that sunny sign separator is used between indexname and culture.

**Comment by persiljehamn** [comment]
Where in epi can i recreate indices?, i think i had missed something. I use cms 11

**Comment by persiljehamn** [comment]
I had found error, why it not workning (no solution yest)
Connection works without problems with postman

[2022-11-24T08:57:23,477][WARN ][o.e.h.AbstractHttpServerTransport] [LNOR080045] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/192.168.202.1:9200, remoteAddress=/192.168.202.1:63333}io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Invalid Alert message: no sufficient data
        at io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
        at io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
