### ISSUE TITLE
failed to parse field [ParentLink] of type [long] in document with id '77__CatalogContent'. Preview of field's value: '1073741825__CatalogContent'

### ISSUE THREAD

**Issue by jorgenhelgheim** [Epinova/Epinova.Elasticsearch#190]
I get this error and stacktrace saveing commerce content using
  <package id="Epinova.ElasticSearch.Core" version="11.7.4.250" targetFramework="net48" />
  <package id="Epinova.ElasticSearch.Core.EPiServer" version="11.7.4.250" targetFramework="net48" />

Error message: failed to parse field [ParentLink] of type [long] in document with id '77__CatalogContent'. Preview of field's value: '1073741825__CatalogContent'

StackTrace:
   at Epinova.ElasticSearch.Core.Utilities.HttpClientHelper.LogAndThrowIfNotSuccess(HttpResponseMessage response)
   at Epinova.ElasticSearch.Core.Utilities.HttpClientHelper.Put(Uri uri, Byte[] data)
   at Epinova.ElasticSearch.Core.CoreIndexer.PerformUpdate(String id, Object objectToUpdate, Type objectType, String indexName)
   at Epinova.ElasticSearch.Core.EPiServer.Indexer.Update(IContent content, String indexName)
   at Epinova.ElasticSearch.Core.EPiServer.Events.IndexingEvents.HandleSaveEvent(SaveContentEventArgs args)
   at Epinova.ElasticSearch.Core.EPiServer.Events.IndexingEvents.UpdateIndex(Object sender, ContentEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at EPiServer.Core.Internal.DefaultContentEvents.RaiseContentEvent(String key, ContentEventArgs eventArgs)
   at EPiServer.Core.Internal.DefaultContentRepository.RaisePostSaveEvents(SaveContentEventArgs eventArgs, StatusTransition transition, Boolean isNew, Boolean isNewLanguageBranch)
   at EPiServer.Core.Internal.DefaultContentRepository.Save(IContent content, SaveAction action, AccessLevel access)
   at MySite.Web.ScheduledJobs.ImportJob.SaveVariant(Variation variation, IContentRepository contentRepo) in C:\.....\ImportJob.cs:line 136
   at MySite.Web.ScheduledJobs.ImportJob.Update(TypeData myObject, ContentReference& ref, JobStatus& status) 
   
   The same ting happens on save in the edit interface of Optimizely, since the HandleSaveEvent occures every time the variant is saves.  

Ofcourse excluding CatalogContentBase type from being indexed, make save possible.

**Comment by jorgenhelgheim** [comment]
Suggestion. Include information in the message indicating the source of this (and other) errors.

**Comment by otanum** [comment]
11.8.20
